services:

  # --- PostgreSQL (for Jenkins pipeline) ---
  postgres:
    image: postgres:15
    container_name: de3-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankingdb
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - jenkins-network

networks:
  jenkins-network:
    name: jenkins-network
    external: true

volumes:
  postgres-data:
