connector.name=iceberg

# Use JDBC catalog so Trino can read Iceberg metadata
iceberg.catalog.type=jdbc

# Store Iceberg catalog metadata tables in Postgres
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://host.docker.internal:5433/bankingdb
iceberg.jdbc-catalog.connection-user=postgres
iceberg.jdbc-catalog.connection-password=password

# Where the Iceberg data files live
iceberg.jdbc-catalog.default-warehouse-dir=file:/opt/spark/work-dir/iceberg_warehouse
